version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    networks:
      - app-net

  # kafka:
  #   image: confluentinc/cp-kafka:7.5.0
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_LISTENERS: PLAINTEXT://:9092
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  #     ALLOW_PLAINTEXT_LISTENER: "yes"
  #   ports:
  #     - "9092:9092"
  #   depends_on:
  #     - zookeeper
  #   networks:
  #     - app-net

  # zookeeper:
  #   image: confluentinc/cp-zookeeper:7.5.0
  #   environment:
  #     ALLOW_ANONYMOUS_LOGIN: "yes"
  #   ports:
  #     - "2181:2181"
  #   networks:
  #     - app-net

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/appdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - db
      # - kafka
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
